version: "2.1"

x-s6-service: &s6-service
  restart: "on-failure"
  tmpfs:
    - /tmp
  environment: &s6-environment
    S6_VERBOSITY: 2
    PUID: "1000"
    PGID: "1000"
  entrypoint:
    - /bin/bash
    - -c
  command:
    - |
      if [[ ${DISABLE,,} =~ true|yes|on|1 ]]; then
        echo "DISABLE is truthy, exiting..."
        exit 0
      fi
      exec /init

volumes:
  downloads: {}
  duplicati: {}
  jellyfin: {}
  letsencrypt: {}
  netdatalib: {}
  netdatacache: {}
  nzbhydra: {}
  plex: {}
  profilarr: {}
  prowlarr: {}
  proxy: {}
  radarr: {}
  sabnzbd: {}
  sonarr: {}
  syncthing: {}
  tautulli: {}
  tailscale: {}
  tailscale-run: {}

services:

  # https://github.com/klutchell/balena-tailscale
  tailscale:
    build: tailscale
    restart: "on-failure"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    labels:
      io.balena.features.kernel-modules: 1
    environment:
      TS_HOSTNAME: mediaserver
    volumes:
      - tailscale:/var/lib/tailscale
      - tailscale-run:/var/run/tailscale
    network_mode: host

  # https://github.com/marvinvr/docktail
  docktail:
    image: ghcr.io/marvinvr/docktail:1.4.1@sha256:f5c8d8616caec42de0e130286d217cff5d42e567ae9afeed593ec5589acb1aca
    labels:
      io.balena.features.balena-socket: 1
    environment:
      DOCKER_HOST: unix:///var/run/balena.sock
      TAILSCALE_SOCKET: /var/run/tailscale/tailscaled.sock
      LOG_LEVEL: info
      RECONCILE_INTERVAL: 60s
    volumes:
      - tailscale-run:/var/run/tailscale

  # https://hub.docker.com/r/jc21/nginx-proxy-manager
  # https://github.com/NginxProxyManager/nginx-proxy-manager
  # https://nginxproxymanager.com/
  nginx:
    <<: *s6-service
    image: jc21/nginx-proxy-manager:2.14.0@sha256:2aa69b382a384b676c0d4f1d6f2eac40ecd478fcf7af1cfb3f9f1d3cd0c81e12
    volumes:
      - proxy:/data
      - letsencrypt:/etc/letsencrypt
    ports:
      - 80:80/tcp
      - 443:443/tcp
      - 127.0.0.1:81:81/tcp
    labels:
      docktail.service.enable: true
      docktail.service.name: nginx-mediaserver
      docktail.service.port: 81
      docktail.service.protocol: http
      docktail.service.service-port: 443
      docktail.service.service-protocol: https

  # https://docs.linuxserver.io/images/docker-duplicati
  duplicati:
    <<: *s6-service
    image: lscr.io/linuxserver/duplicati:2.3.0@sha256:e13e45989514928a22c5209019c51af8aa83233f378e32498fe8a0f6ec10cc7b
    environment:
      <<: *s6-environment
      PUID: "0"
      PGID: "0"
    volumes:
      - duplicati:/config
      # any volumes that might be worth backing up
      - syncthing:/volumes/syncthing
      - plex:/volumes/plex
      - sonarr:/volumes/sonarr
      - radarr:/volumes/radarr
      - nzbhydra:/volumes/nzbhydra
      - jellyfin:/volumes/jellyfin
      - prowlarr:/volumes/prowlarr
      - profilarr:/volumes/profilarr
      - sabnzbd:/volumes/sabnzbd
      - downloads:/volumes/downloads
      - proxy:/volumes/proxy
      - letsencrypt:/volumes/letsencrypt
      - tautulli:/volumes/tautulli
    ports:
      - 127.0.0.1:8200:8200/tcp
    labels:
      # https://github.com/marvinvr/docktail
      docktail.service.enable: true
      docktail.service.name: duplicati-mediaserver
      docktail.service.port: 8200
      docktail.service.protocol: http
      docktail.service.service-port: 443
      docktail.service.service-protocol: https

  # https://docs.linuxserver.io/images/docker-jellyfin
  jellyfin:
    <<: *s6-service
    image: lscr.io/linuxserver/jellyfin:10.11.8@sha256:ae1ac3d89b8598f31f5e1dc5aff898e13eab617303db58f84956e26f7b78c198
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - jellyfin:/config
      - downloads:/downloads
    ports:
      - 127.0.0.1:8096:8096/tcp
    labels:
      # https://github.com/marvinvr/docktail
      docktail.service.enable: true
      docktail.service.name: jellyfin
      docktail.service.port: 8096
      docktail.service.protocol: http
      docktail.service.service-port: 443
      docktail.service.service-protocol: https
      # docktail.funnel.enable: true # Enable public internet access
      # docktail.funnel.port: 8096 # Container port for funnel

  # https://docs.linuxserver.io/images/docker-nzbhydra
  nzbhydra:
    <<: *s6-service
    image: lscr.io/linuxserver/nzbhydra2:8.8.1@sha256:c10777a378f5f48079f6a69c933e53793edf2e09e92540b9bcdcad20a0c1f986
    volumes:
      - nzbhydra:/config
      - downloads:/downloads
    ports:
      - 127.0.0.1:5076:5076/tcp
    labels:
      # https://github.com/marvinvr/docktail
      docktail.service.enable: true
      docktail.service.name: nzbhydra
      docktail.service.port: 5076
      docktail.service.protocol: http
      docktail.service.service-port: 443
      docktail.service.service-protocol: https

  # https://docs.linuxserver.io/images/docker-plex
  plex:
    <<: *s6-service
    image: lscr.io/linuxserver/plex:1.43.1@sha256:e5c7c283b242966416a4bed2d666acf6f3fb8f957c704be8333f8dc987364825
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - plex:/config
      - downloads:/downloads
    ports:
      - 127.0.0.1:32400:32400/tcp
    labels:
      # https://github.com/marvinvr/docktail
      docktail.service.enable: true
      docktail.service.name: plex
      docktail.service.port: 32400
      docktail.service.protocol: http
      docktail.service.service-port: 443
      docktail.service.service-protocol: https
      # docktail.funnel.enable: true # Enable public internet access
      # docktail.funnel.port: 32400 # Container port for funnel

  # https://docs.linuxserver.io/images/docker-prowlarr
  prowlarr:
    <<: *s6-service
    image: lscr.io/linuxserver/prowlarr:2.3.5@sha256:c5de2a8758a05594319263e7691c1dce56899442ed1720d6eca216c0958f4caf
    volumes:
      - prowlarr:/config
      - downloads:/downloads
    ports:
      - 127.0.0.1:9696:9696/tcp
    labels:
      # https://github.com/marvinvr/docktail
      docktail.service.enable: true
      docktail.service.name: prowlarr
      docktail.service.port: 9696
      docktail.service.protocol: http
      docktail.service.service-port: 443
      docktail.service.service-protocol: https

  # https://github.com/Dictionarry-Hub/profilarr
  # https://dictionarry.dev/profilarr-setup/installation
  profilarr:
    restart: "on-failure"
    image: santiagosayshey/profilarr:v1.1.4@sha256:8a514f8429cd33885166facc9eb6504fa9ded056c737609e5e8ef32ae0afb350
    tmpfs:
      - /tmp
    entrypoint:
      - /bin/bash
      - -c
    command:
      - |
        if [[ ${DISABLE,,} =~ true|yes|on|1 ]]; then
          echo "DISABLE is truthy, exiting..."
          exit 0
        fi
        exec /entrypoint.sh gunicorn --bind 0.0.0.0:6868 --timeout 600 'app.main:create_app()'
    volumes:
      - profilarr:/config
    ports:
      - 127.0.0.1:6868:6868/tcp
    labels:
      # https://github.com/marvinvr/docktail
      docktail.service.enable: true
      docktail.service.name: profilarr
      docktail.service.port: 6868
      docktail.service.protocol: http
      docktail.service.service-port: 443
      docktail.service.service-protocol: https

  # https://docs.linuxserver.io/images/docker-radarr
  radarr:
    <<: *s6-service
    image: lscr.io/linuxserver/radarr:6.1.1@sha256:b01097ad2d948c9f5eca39eb60bb529e2e55b0738c4bf7db09383bef0abab59d
    volumes:
      - radarr:/config
      - downloads:/downloads
    ports:
      - 127.0.0.1:7878:7878/tcp
    labels:
      # https://github.com/marvinvr/docktail
      docktail.service.enable: true
      docktail.service.name: radarr
      docktail.service.port: 7878
      docktail.service.protocol: http
      docktail.service.service-port: 443
      docktail.service.service-protocol: https

  # https://docs.linuxserver.io/images/docker-sabnzbd
  sabnzbd:
    <<: *s6-service
    image: lscr.io/linuxserver/sabnzbd:4.5.5@sha256:374051b90f64d107f8658dcd9b9065c28826afe14562647214f45057e119fc04
    volumes:
      - sabnzbd:/config
      - downloads:/downloads
    ports:
      - 127.0.0.1:8080:8080/tcp
    labels:
      # https://github.com/marvinvr/docktail
      docktail.service.enable: true
      docktail.service.name: sabnzbd
      docktail.service.port: 8080
      docktail.service.protocol: http
      docktail.service.service-port: 443
      docktail.service.service-protocol: https

  # https://docs.linuxserver.io/images/docker-sonarr
  sonarr:
    <<: *s6-service
    image: lscr.io/linuxserver/sonarr:4.0.17@sha256:3580aec3802c915f0f819a88d5099abce61734b925732b8393d176b5dc561020
    volumes:
      - sonarr:/config
      - downloads:/downloads
    ports:
      - 127.0.0.1:8989:8989/tcp
    labels:
      # https://github.com/marvinvr/docktail
      docktail.service.enable: true
      docktail.service.name: sonarr
      docktail.service.port: 8989
      docktail.service.protocol: http
      docktail.service.service-port: 443
      docktail.service.service-protocol: https

  # https://docs.linuxserver.io/images/docker-syncthing
  syncthing:
    <<: *s6-service
    image: lscr.io/linuxserver/syncthing:2.0.16@sha256:6a5f5d3412f80539289cee9bd0a6df9645f8540ecaed7d34f1bd0930bfd8c55e
    volumes:
      - syncthing:/config
      # any volumes that might be worth syncronizing between machines
      - plex:/volumes/plex
      - sonarr:/volumes/sonarr
      - radarr:/volumes/radarr
      - nzbhydra:/volumes/nzbhydra
      - jellyfin:/volumes/jellyfin
      - prowlarr:/volumes/prowlarr
      - profilarr:/volumes/profilarr
      - sabnzbd:/volumes/sabnzbd
      - downloads:/volumes/downloads
      - proxy:/volumes/proxy
      - tautulli:/volumes/tautulli
    ports:
      - 127.0.0.1:8384:8384/tcp
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    labels:
      # https://github.com/marvinvr/docktail
      docktail.service.enable: true
      docktail.service.name: syncthing-mediaserver
      docktail.service.port: 8384
      docktail.service.protocol: http
      docktail.service.service-port: 443
      docktail.service.service-protocol: https

  # https://docs.linuxserver.io/images/docker-tautulli
  tautulli:
    <<: *s6-service
    image: lscr.io/linuxserver/tautulli:2.17.0@sha256:8a5fa2a6c585abc64c4ca5423c4a272257363444ed36882ac84ecb6b455da7f0
    volumes:
      - tautulli:/config
    ports:
      - 127.0.0.1:8181:8181/tcp
    labels:
      # https://github.com/marvinvr/docktail
      docktail.service.enable: true
      docktail.service.name: tautulli
      docktail.service.port: 8181
      docktail.service.protocol: http
      docktail.service.service-port: 443
      docktail.service.service-protocol: https

  # https://hub.docker.com/r/netdata/netdata
  netdata:
    image: netdata/netdata:v2.10.2@sha256:27f2b88e470662b5272e458c5dd93807f4b329a72aef551f33593a315f97d2eb
    restart: "on-failure"
    privileged: true
    cap_add:
      - SYS_PTRACE
    environment:
      DOCKER_HOST: "/var/run/balena.sock"
      PGID: "990" # ls -nd /var/run/balena.sock | awk '{print $4}'
    security_opt:
      - apparmor:unconfined
    tmpfs:
      - /tmp
    volumes:
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
    ports:
      - 127.0.0.1:19999:19999/tcp
    labels:
      io.balena.features.balena-socket: 1
      io.balena.features.procfs: 1
      io.balena.features.sysfs: 1
      # https://github.com/marvinvr/docktail
      docktail.service.enable: true
      docktail.service.name: netdata-mediaserver
      docktail.service.port: 19999
      docktail.service.protocol: http
      docktail.service.service-port: 443
      docktail.service.service-protocol: https
