
FROM balenalib/raspberrypi4-64:run

COPY samba.sh /

RUN install_packages samba-client samba \
    && useradd --user-group --no-create-home --shell /usr/sbin/nologin abc \
    # && smbpasswd -n -a abc \
    && chmod a+x /samba.sh

CMD [ "/samba.sh" ]