version: "2.1"

x-s6-service: &s6-service
  restart: "on-failure"
  tmpfs:
    - /tmp
  environment: &s6-environment
    S6_VERBOSITY: 2
    PUID: "1000"
    PGID: "1000"
  entrypoint:
    - /bin/bash
    - -c
  command:
    - |
      if printenv DISABLE | grep -qiE '^(true|yes|on|1)$'; then
        echo "DISABLE is truthy, exiting..."
        exit 0
      fi
      exec /init

volumes:
  downloads: {}
  duplicati: {}
  jellyfin: {}
  letsencrypt: {}
  netdatalib: {}
  netdatacache: {}
  nzbhydra: {}
  plex: {}
  profilarr: {}
  prowlarr: {}
  proxy: {}
  radarr: {}
  sabnzbd: {}
  sonarr: {}
  syncthing: {}
  tautulli: {}
  tailscale: {}
  tailscale-run: {}

services:

  # https://github.com/klutchell/balena-tailscale
  tailscale:
    build: tailscale
    restart: "on-failure"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    labels:
      io.balena.features.kernel-modules: 1
    environment:
      TS_HOSTNAME: mediaserver
    volumes:
      - tailscale:/var/lib/tailscale
      - tailscale-run:/var/run/tailscale
    network_mode: host

  # https://github.com/marvinvr/docktail
  docktail:
    image: ghcr.io/marvinvr/docktail:1.7.5@sha256:e32998ea96d12cb81128e108bab856edf3c5b0f42b31573a39624ee4acbfe165
    labels:
      io.balena.features.balena-socket: 1
    environment:
      DOCKER_HOST: unix:///var/run/balena.sock
      TAILSCALE_SOCKET: /var/run/tailscale/tailscaled.sock
      LOG_LEVEL: info
      RECONCILE_INTERVAL: 60s
    volumes:
      - tailscale-run:/var/run/tailscale

  # https://hub.docker.com/r/jc21/nginx-proxy-manager
  # https://github.com/NginxProxyManager/nginx-proxy-manager
  # https://nginxproxymanager.com/
  nginx:
    <<: *s6-service
    image: jc21/nginx-proxy-manager:2.15.1@sha256:52b2c59994f3d36acfcf70a1626f29734df0ed8c71bacc0269f78b6f939858bb
    volumes:
      - proxy:/data
      - letsencrypt:/etc/letsencrypt
    ports:
      - 80:80/tcp
      - 443:443/tcp
      - 127.0.0.1:81:81/tcp
    labels:
      docktail.service.enable: true
      docktail.service.name: nginx-mediaserver
      docktail.service.port: 81
      docktail.service.protocol: http
      docktail.service.service-port: 443
      docktail.service.service-protocol: https

  # https://docs.linuxserver.io/images/docker-duplicati
  duplicati:
    <<: *s6-service
    image: lscr.io/linuxserver/duplicati:2.3.0@sha256:9166c91eeef6965acf1b80f694ab03738fc143d1ff4e7be0c1d6a1bc89a24ed3
    environment:
      <<: *s6-environment
      PUID: "0"
      PGID: "0"
    volumes:
      - duplicati:/config
      # any volumes that might be worth backing up
      - syncthing:/volumes/syncthing
      - plex:/volumes/plex
      - sonarr:/volumes/sonarr
      - radarr:/volumes/radarr
      - nzbhydra:/volumes/nzbhydra
      - jellyfin:/volumes/jellyfin
      - prowlarr:/volumes/prowlarr
      - profilarr:/volumes/profilarr
      - sabnzbd:/volumes/sabnzbd
      - downloads:/volumes/downloads
      - proxy:/volumes/proxy
      - letsencrypt:/volumes/letsencrypt
      - tautulli:/volumes/tautulli
    ports:
      - 127.0.0.1:8200:8200/tcp
    labels:
      # https://github.com/marvinvr/docktail
      docktail.service.enable: true
      docktail.service.name: duplicati-mediaserver
      docktail.service.port: 8200
      docktail.service.protocol: http
      docktail.service.service-port: 443
      docktail.service.service-protocol: https

  # https://docs.linuxserver.io/images/docker-jellyfin
  jellyfin:
    <<: *s6-service
    image: lscr.io/linuxserver/jellyfin:10.11.11@sha256:b8dcc7b71d0ea872b74314da4b995c0cf282b1778438c295996e7be88c70fdda
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - jellyfin:/config
      - downloads:/downloads
    ports:
      - 127.0.0.1:8096:8096/tcp
    labels:
      # https://github.com/marvinvr/docktail
      docktail.service.enable: true
      docktail.service.name: jellyfin
      docktail.service.port: 8096
      docktail.service.protocol: http
      docktail.service.service-port: 443
      docktail.service.service-protocol: https
      # docktail.funnel.enable: true # Enable public internet access
      # docktail.funnel.port: 8096 # Container port for funnel

  # https://docs.linuxserver.io/images/docker-nzbhydra
  nzbhydra:
    <<: *s6-service
    image: lscr.io/linuxserver/nzbhydra2:8.9.0@sha256:fa8d20f4fba6203d8046ac6f656eb44b3907e51fa18000829905464f58444988
    volumes:
      - nzbhydra:/config
      - downloads:/downloads
    ports:
      - 127.0.0.1:5076:5076/tcp
    labels:
      # https://github.com/marvinvr/docktail
      docktail.service.enable: true
      docktail.service.name: nzbhydra
      docktail.service.port: 5076
      docktail.service.protocol: http
      docktail.service.service-port: 443
      docktail.service.service-protocol: https

  # https://docs.linuxserver.io/images/docker-plex
  plex:
    <<: *s6-service
    image: lscr.io/linuxserver/plex:1.43.3@sha256:d8b3417b9173bab8bb79b167119b6b69a85558f2127e7fa810a045654e3dbe7f
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - plex:/config
      - downloads:/downloads
    ports:
      - 127.0.0.1:32400:32400/tcp
    labels:
      # https://github.com/marvinvr/docktail
      docktail.service.enable: true
      docktail.service.name: plex
      docktail.service.port: 32400
      docktail.service.protocol: http
      docktail.service.service-port: 443
      docktail.service.service-protocol: https
      # docktail.funnel.enable: true # Enable public internet access
      # docktail.funnel.port: 32400 # Container port for funnel

  # https://docs.linuxserver.io/images/docker-prowlarr
  prowlarr:
    <<: *s6-service
    image: lscr.io/linuxserver/prowlarr:2.5.2@sha256:1295cff29d10b486c0d8324d1559a552140a5932bf8b3d87e398654414f63f92
    volumes:
      - prowlarr:/config
      - downloads:/downloads
    ports:
      - 127.0.0.1:9696:9696/tcp
    labels:
      # https://github.com/marvinvr/docktail
      docktail.service.enable: true
      docktail.service.name: prowlarr
      docktail.service.port: 9696
      docktail.service.protocol: http
      docktail.service.service-port: 443
      docktail.service.service-protocol: https

  # https://github.com/Dictionarry-Hub/profilarr
  # https://dictionarry.dev/profilarr-setup/installation
  profilarr:
    restart: "on-failure"
    image: santiagosayshey/profilarr:v1.1.5@sha256:8033e9c6d6995f37625afeb93d7020e99566f549ae83b65f1db7e11048952d0f
    tmpfs:
      - /tmp
    entrypoint:
      - /bin/bash
      - -c
    command:
      - |
        if printenv DISABLE | grep -qiE '^(true|yes|on|1)$'; then
          echo "DISABLE is truthy, exiting..."
          exit 0
        fi
        exec /entrypoint.sh gunicorn --bind 0.0.0.0:6868 --timeout 600 'app.main:create_app()'
    volumes:
      - profilarr:/config
    ports:
      - 127.0.0.1:6868:6868/tcp
    labels:
      # https://github.com/marvinvr/docktail
      docktail.service.enable: true
      docktail.service.name: profilarr
      docktail.service.port: 6868
      docktail.service.protocol: http
      docktail.service.service-port: 443
      docktail.service.service-protocol: https

  # https://docs.linuxserver.io/images/docker-radarr
  radarr:
    <<: *s6-service
    image: lscr.io/linuxserver/radarr:6.3.0@sha256:a45b5ab0f850f39edb4cc9c95bbd967b52ddc3d4574a4dfb45561177db6c88f4
    volumes:
      - radarr:/config
      - downloads:/downloads
    ports:
      - 127.0.0.1:7878:7878/tcp
    labels:
      # https://github.com/marvinvr/docktail
      docktail.service.enable: true
      docktail.service.name: radarr
      docktail.service.port: 7878
      docktail.service.protocol: http
      docktail.service.service-port: 443
      docktail.service.service-protocol: https

  # https://docs.linuxserver.io/images/docker-sabnzbd
  sabnzbd:
    <<: *s6-service
    image: lscr.io/linuxserver/sabnzbd:5.0.4@sha256:4307a4ef4a1687c6f7dfa36fc745c1fc10b78db9916b64970b9ff682539dd03b
    volumes:
      - sabnzbd:/config
      - downloads:/downloads
    ports:
      - 127.0.0.1:8080:8080/tcp
    labels:
      # https://github.com/marvinvr/docktail
      docktail.service.enable: true
      docktail.service.name: sabnzbd
      docktail.service.port: 8080
      docktail.service.protocol: http
      docktail.service.service-port: 443
      docktail.service.service-protocol: https

  # https://docs.linuxserver.io/images/docker-sonarr
  sonarr:
    <<: *s6-service
    image: lscr.io/linuxserver/sonarr:4.0.19@sha256:373159ba768e23a3a1c497d9f2b936addf8fd5b1fdce7dd6a14080ac928bfda0
    volumes:
      - sonarr:/config
      - downloads:/downloads
    ports:
      - 127.0.0.1:8989:8989/tcp
    labels:
      # https://github.com/marvinvr/docktail
      docktail.service.enable: true
      docktail.service.name: sonarr
      docktail.service.port: 8989
      docktail.service.protocol: http
      docktail.service.service-port: 443
      docktail.service.service-protocol: https

  # https://docs.linuxserver.io/images/docker-syncthing
  syncthing:
    <<: *s6-service
    image: lscr.io/linuxserver/syncthing:2.1.3@sha256:07da4c778027cb13d4a2b9bb8b8d7432ac3a0f0540bb7248b016be3a1cc69788
    volumes:
      - syncthing:/config
      # any volumes that might be worth syncronizing between machines
      - plex:/volumes/plex
      - sonarr:/volumes/sonarr
      - radarr:/volumes/radarr
      - nzbhydra:/volumes/nzbhydra
      - jellyfin:/volumes/jellyfin
      - prowlarr:/volumes/prowlarr
      - profilarr:/volumes/profilarr
      - sabnzbd:/volumes/sabnzbd
      - downloads:/volumes/downloads
      - proxy:/volumes/proxy
      - tautulli:/volumes/tautulli
    ports:
      - 127.0.0.1:8384:8384/tcp
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    labels:
      # https://github.com/marvinvr/docktail
      docktail.service.enable: true
      docktail.service.name: syncthing-mediaserver
      docktail.service.port: 8384
      docktail.service.protocol: http
      docktail.service.service-port: 443
      docktail.service.service-protocol: https

  # https://docs.linuxserver.io/images/docker-tautulli
  tautulli:
    <<: *s6-service
    image: lscr.io/linuxserver/tautulli:2.17.2@sha256:5a6501710790b545693de2938bdfd279d52291f986b6f7273716783b2b080cc6
    volumes:
      - tautulli:/config
    ports:
      - 127.0.0.1:8181:8181/tcp
    labels:
      # https://github.com/marvinvr/docktail
      docktail.service.enable: true
      docktail.service.name: tautulli
      docktail.service.port: 8181
      docktail.service.protocol: http
      docktail.service.service-port: 443
      docktail.service.service-protocol: https

  # https://hub.docker.com/r/netdata/netdata
  netdata:
    image: netdata/netdata:v2.10.4@sha256:689145f603fed0ca341b4d8a0fb9910cd9d8c0590b0530cd24ae1912a9c7f8f3
    restart: "on-failure"
    privileged: true
    cap_add:
      - SYS_PTRACE
    environment:
      DOCKER_HOST: "/var/run/balena.sock"
      PGID: "990" # ls -nd /var/run/balena.sock | awk '{print $4}'
    security_opt:
      - apparmor:unconfined
    tmpfs:
      - /tmp
    volumes:
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
    ports:
      - 127.0.0.1:19999:19999/tcp
    labels:
      io.balena.features.balena-socket: 1
      io.balena.features.procfs: 1
      io.balena.features.sysfs: 1
      # https://github.com/marvinvr/docktail
      docktail.service.enable: true
      docktail.service.name: netdata-mediaserver
      docktail.service.port: 19999
      docktail.service.protocol: http
      docktail.service.service-port: 443
      docktail.service.service-protocol: https
