version: "2.1"

x-s6-service: &s6-service
  restart: "on-failure"
  tmpfs:
    - /tmp
  environment: &s6-environment
    S6_VERBOSITY: 2
    PUID: "1000"
    PGID: "1000"
  entrypoint:
    - /bin/bash
    - -c
  command:
    - |
      if [[ ${DISABLE,,} =~ true|yes|on|1 ]]; then
        echo "DISABLE is truthy, exiting..."
        exit 0
      fi
      exec /init

volumes:
  downloads: {}
  duplicati: {}
  jellyfin: {}
  letsencrypt: {}
  netdatalib: {}
  netdatacache: {}
  nzbhydra: {}
  plex: {}
  profilarr: {}
  prowlarr: {}
  proxy: {}
  radarr: {}
  sabnzbd: {}
  sonarr: {}
  syncthing: {}
  tautulli: {}
  tailscale: {}
  tailscale-run: {}

services:

  # https://github.com/klutchell/balena-tailscale
  tailscale:
    build: tailscale
    restart: "on-failure"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    labels:
      io.balena.features.kernel-modules: 1
    environment:
      TS_HOSTNAME: mediaserver
    volumes:
      - tailscale:/var/lib/tailscale
      - tailscale-run:/var/run/tailscale
    network_mode: host

  # https://github.com/marvinvr/docktail
  docktail:
    image: ghcr.io/marvinvr/docktail:1.2.2@sha256:8144912b91bcfecf1b967811f73ebd53c580c36141850e7936a8f0b6a4e6aa31
    labels:
      io.balena.features.balena-socket: 1
    environment:
      DOCKER_HOST: unix:///var/run/balena.sock
      TAILSCALE_SOCKET: /var/run/tailscale/tailscaled.sock
      LOG_LEVEL: info
      RECONCILE_INTERVAL: 60s
    volumes:
      - tailscale-run:/var/run/tailscale

  # https://hub.docker.com/r/jc21/nginx-proxy-manager
  # https://github.com/NginxProxyManager/nginx-proxy-manager
  # https://nginxproxymanager.com/
  nginx:
    <<: *s6-service
    image: jc21/nginx-proxy-manager:2.14.0@sha256:2aa69b382a384b676c0d4f1d6f2eac40ecd478fcf7af1cfb3f9f1d3cd0c81e12
    volumes:
      - proxy:/data
      - letsencrypt:/etc/letsencrypt
    ports:
      - 80:80/tcp
      - 443:443/tcp
      - 127.0.0.1:81:81/tcp
    labels:
      docktail.service.enable: true
      docktail.service.name: nginx-mediaserver
      docktail.service.port: 81
      docktail.service.protocol: http
      docktail.service.service-port: 443
      docktail.service.service-protocol: https

  # https://docs.linuxserver.io/images/docker-duplicati
  duplicati:
    <<: *s6-service
    image: lscr.io/linuxserver/duplicati:2.2.0@sha256:b166f07cf80a107a41909d0dfa281fd88a267dd30f6372f8ad9c8f6cc4a298ac
    environment:
      <<: *s6-environment
      PUID: "0"
      PGID: "0"
    volumes:
      - duplicati:/config
      # any volumes that might be worth backing up
      - syncthing:/volumes/syncthing
      - plex:/volumes/plex
      - sonarr:/volumes/sonarr
      - radarr:/volumes/radarr
      - nzbhydra:/volumes/nzbhydra
      - jellyfin:/volumes/jellyfin
      - prowlarr:/volumes/prowlarr
      - profilarr:/volumes/profilarr
      - sabnzbd:/volumes/sabnzbd
      - downloads:/volumes/downloads
      - proxy:/volumes/proxy
      - letsencrypt:/volumes/letsencrypt
      - tautulli:/volumes/tautulli
    ports:
      - 127.0.0.1:8200:8200/tcp
    labels:
      # https://github.com/marvinvr/docktail
      docktail.service.enable: true
      docktail.service.name: duplicati-mediaserver
      docktail.service.port: 8200
      docktail.service.protocol: http
      docktail.service.service-port: 443
      docktail.service.service-protocol: https

  # https://docs.linuxserver.io/images/docker-jellyfin
  jellyfin:
    <<: *s6-service
    image: lscr.io/linuxserver/jellyfin:10.11.6@sha256:0a2f7e2c1c34e1a0e553b8521208ac1cc9ffa6a0efc2cf4acb4a45229b390e65
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - jellyfin:/config
      - downloads:/downloads
    ports:
      - 127.0.0.1:8096:8096/tcp
    labels:
      # https://github.com/marvinvr/docktail
      docktail.service.enable: true
      docktail.service.name: jellyfin
      docktail.service.port: 8096
      docktail.service.protocol: http
      docktail.service.service-port: 443
      docktail.service.service-protocol: https
      # docktail.funnel.enable: true # Enable public internet access
      # docktail.funnel.port: 8096 # Container port for funnel

  # https://docs.linuxserver.io/images/docker-nzbhydra
  nzbhydra:
    <<: *s6-service
    image: lscr.io/linuxserver/nzbhydra2:8.5.2@sha256:ec2c2d60f6da4fe91b8cc9bfae3c779679318d14fb17694012ff05765f39b4ac
    volumes:
      - nzbhydra:/config
      - downloads:/downloads
    ports:
      - 127.0.0.1:5076:5076/tcp
    labels:
      # https://github.com/marvinvr/docktail
      docktail.service.enable: true
      docktail.service.name: nzbhydra
      docktail.service.port: 5076
      docktail.service.protocol: http
      docktail.service.service-port: 443
      docktail.service.service-protocol: https

  # https://docs.linuxserver.io/images/docker-plex
  plex:
    <<: *s6-service
    image: lscr.io/linuxserver/plex:1.43.0@sha256:a27f1ce1e1d14cd3627ed217f042bf8de0f796ed274fb27b2dc971ae22a64b95
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - plex:/config
      - downloads:/downloads
    ports:
      - 127.0.0.1:32400:32400/tcp
    labels:
      # https://github.com/marvinvr/docktail
      docktail.service.enable: true
      docktail.service.name: plex
      docktail.service.port: 32400
      docktail.service.protocol: http
      docktail.service.service-port: 443
      docktail.service.service-protocol: https
      # docktail.funnel.enable: true # Enable public internet access
      # docktail.funnel.port: 32400 # Container port for funnel

  # https://docs.linuxserver.io/images/docker-prowlarr
  prowlarr:
    <<: *s6-service
    image: lscr.io/linuxserver/prowlarr:2.3.0@sha256:9ef5d8bf832edcacb6082f9262cb36087854e78eb7b1c3e1d4375056055b2d82
    volumes:
      - prowlarr:/config
      - downloads:/downloads
    ports:
      - 127.0.0.1:9696:9696/tcp
    labels:
      # https://github.com/marvinvr/docktail
      docktail.service.enable: true
      docktail.service.name: prowlarr
      docktail.service.port: 9696
      docktail.service.protocol: http
      docktail.service.service-port: 443
      docktail.service.service-protocol: https

  # https://github.com/Dictionarry-Hub/profilarr
  # https://dictionarry.dev/profilarr-setup/installation
  profilarr:
    restart: "on-failure"
    image: santiagosayshey/profilarr:v1.1.4@sha256:8a514f8429cd33885166facc9eb6504fa9ded056c737609e5e8ef32ae0afb350
    tmpfs:
      - /tmp
    entrypoint:
      - /bin/bash
      - -c
    command:
      - |
        if [[ ${DISABLE,,} =~ true|yes|on|1 ]]; then
          echo "DISABLE is truthy, exiting..."
          exit 0
        fi
        exec /entrypoint.sh gunicorn --bind 0.0.0.0:6868 --timeout 600 'app.main:create_app()'
    volumes:
      - profilarr:/config
    ports:
      - 127.0.0.1:6868:6868/tcp
    labels:
      # https://github.com/marvinvr/docktail
      docktail.service.enable: true
      docktail.service.name: profilarr
      docktail.service.port: 6868
      docktail.service.protocol: http
      docktail.service.service-port: 443
      docktail.service.service-protocol: https

  # https://docs.linuxserver.io/images/docker-radarr
  radarr:
    <<: *s6-service
    image: lscr.io/linuxserver/radarr:6.0.4@sha256:ca43905eaf2dd11425efdcfe184892e43806b1ae0a830440c825cecbc2629cfb
    volumes:
      - radarr:/config
      - downloads:/downloads
    ports:
      - 127.0.0.1:7878:7878/tcp
    labels:
      # https://github.com/marvinvr/docktail
      docktail.service.enable: true
      docktail.service.name: radarr
      docktail.service.port: 7878
      docktail.service.protocol: http
      docktail.service.service-port: 443
      docktail.service.service-protocol: https

  # https://docs.linuxserver.io/images/docker-sabnzbd
  sabnzbd:
    <<: *s6-service
    image: lscr.io/linuxserver/sabnzbd:4.5.5@sha256:15b1220aaa1f8ff428790a3d56f5ca2822427ea0b33e978eee43554e42579d0f
    volumes:
      - sabnzbd:/config
      - downloads:/downloads
    ports:
      - 127.0.0.1:8080:8080/tcp
    labels:
      # https://github.com/marvinvr/docktail
      docktail.service.enable: true
      docktail.service.name: sabnzbd
      docktail.service.port: 8080
      docktail.service.protocol: http
      docktail.service.service-port: 443
      docktail.service.service-protocol: https

  # https://docs.linuxserver.io/images/docker-sonarr
  sonarr:
    <<: *s6-service
    image: lscr.io/linuxserver/sonarr:4.0.17@sha256:76414c033f290d3c9f1f9dfad71150abe71d92592369a3377a5903d579e6e2b2
    volumes:
      - sonarr:/config
      - downloads:/downloads
    ports:
      - 127.0.0.1:8989:8989/tcp
    labels:
      # https://github.com/marvinvr/docktail
      docktail.service.enable: true
      docktail.service.name: sonarr
      docktail.service.port: 8989
      docktail.service.protocol: http
      docktail.service.service-port: 443
      docktail.service.service-protocol: https

  # https://docs.linuxserver.io/images/docker-syncthing
  syncthing:
    <<: *s6-service
    image: lscr.io/linuxserver/syncthing:2.0.15@sha256:befb3dc3efac8987270fa6fa99d9594a0dc2a11662b720a296453e162a274149
    volumes:
      - syncthing:/config
      # any volumes that might be worth syncronizing between machines
      - plex:/volumes/plex
      - sonarr:/volumes/sonarr
      - radarr:/volumes/radarr
      - nzbhydra:/volumes/nzbhydra
      - jellyfin:/volumes/jellyfin
      - prowlarr:/volumes/prowlarr
      - profilarr:/volumes/profilarr
      - sabnzbd:/volumes/sabnzbd
      - downloads:/volumes/downloads
      - proxy:/volumes/proxy
      - tautulli:/volumes/tautulli
    ports:
      - 127.0.0.1:8384:8384/tcp
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    labels:
      # https://github.com/marvinvr/docktail
      docktail.service.enable: true
      docktail.service.name: syncthing-mediaserver
      docktail.service.port: 8384
      docktail.service.protocol: http
      docktail.service.service-port: 443
      docktail.service.service-protocol: https

  # https://docs.linuxserver.io/images/docker-tautulli
  tautulli:
    <<: *s6-service
    image: lscr.io/linuxserver/tautulli:2.16.1@sha256:f7e8a00e81a216835d19d5f6219c31998ec844046d09326a682594c197911a75
    volumes:
      - tautulli:/config
    ports:
      - 127.0.0.1:8181:8181/tcp
    labels:
      # https://github.com/marvinvr/docktail
      docktail.service.enable: true
      docktail.service.name: tautulli
      docktail.service.port: 8181
      docktail.service.protocol: http
      docktail.service.service-port: 443
      docktail.service.service-protocol: https

  # https://hub.docker.com/r/netdata/netdata
  netdata:
    image: netdata/netdata:v2.9.0@sha256:4cbe33f6fc317a7f5c453c8b4997316e4e320a7abd8cc921cecba98f2a5cbcf5
    restart: "on-failure"
    privileged: true
    cap_add:
      - SYS_PTRACE
    environment:
      DOCKER_HOST: "/var/run/balena.sock"
      PGID: "990" # ls -nd /var/run/balena.sock | awk '{print $4}'
    security_opt:
      - apparmor:unconfined
    tmpfs:
      - /tmp
    volumes:
      - netdatalib:/var/lib/netdata
      - netdatacache:/var/cache/netdata
    ports:
      - 127.0.0.1:19999:19999/tcp
    labels:
      io.balena.features.balena-socket: 1
      io.balena.features.procfs: 1
      io.balena.features.sysfs: 1
      # https://github.com/marvinvr/docktail
      docktail.service.enable: true
      docktail.service.name: netdata-mediaserver
      docktail.service.port: 19999
      docktail.service.protocol: http
      docktail.service.service-port: 443
      docktail.service.service-protocol: https
