
ARG BALENA_ARCH=%%BALENA_ARCH%%

FROM bh.cr/gh_klutchell/tailscale-amd64/e0deb8be662109e58eb98375d4b2c096:1.102.3 AS balena-tailscale-amd64
FROM bh.cr/gh_klutchell/tailscale-aarch64/c00ef0c728f91f7f1f6154ed0c6542ca:1.102.3 AS balena-tailscale-aarch64
FROM bh.cr/gh_klutchell/tailscale-armv7hf/40ec2348fe8993cf7770dac70485e589:1.102.3 AS balena-tailscale-armv7hf

# hadolint ignore=DL3006
FROM balena-tailscale-${BALENA_ARCH}
