
ARG BALENA_ARCH=%%BALENA_ARCH%%

FROM bh.cr/gh_klutchell/tailscale-amd64/2bcc96e6c9e2eb87797d25ab3582b25a:1.102.3-rev3 AS balena-tailscale-amd64
FROM bh.cr/gh_klutchell/tailscale-aarch64/6980eaefd0f3809fdb883618d83c22ec:1.102.3-rev3 AS balena-tailscale-aarch64
FROM bh.cr/gh_klutchell/tailscale-armv7hf/dc8d131a7be5862a263cab0663d3c57d:1.102.3-rev3 AS balena-tailscale-armv7hf

# hadolint ignore=DL3006
FROM balena-tailscale-${BALENA_ARCH}
