#!/command/with-contenv bash
# shellcheck shell=bash

# https://github.com/tailscale-dev/docker-mod/blob/main/root/etc/s6-overlay/s6-rc.d/svc-tailscale/run

set -euo pipefail

FLAGS="--tun=userspace-networking"

# https://github.com/tailscale-dev/docker-mod/pull/8#issuecomment-1792262196
# https://tailscale.com/kb/1112/userspace-networking/
if [ -v TAILSCALE_USE_EXIT_NODE ]; then
    FLAGS="$FLAGS --socks5-server=localhost:3215 --outbound-http-proxy-listen=localhost:3214"
fi

if [ -v TAILSCALE_STATE_DIR ]; then
    mkdir -p "${TAILSCALE_STATE_DIR}"
    FLAGS="$FLAGS --statedir=${TAILSCALE_STATE_DIR}"
else
    FLAGS="$FLAGS --state=mem:"
fi

# shellcheck disable=SC2086
tailscaled $FLAGS 2>&1 &
pid=$!

# https://github.com/just-containers/s6-overlay/issues/545
graceful_stop() {
    # https://tailscale.com/kb/1080/cli/#down
    tailscale down --accept-risk=all
    kill -QUIT $pid
}

trap "graceful_stop; exit" SIGTERM SIGQUIT

wait $pid
