name: Flowzone

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches: [main, master]
  push:
    branches: [main, master]

jobs:
  flowzone:
    name: Flowzone
    uses: product-os/flowzone/.github/workflows/flowzone.yml@6ed3768db0119a86880552b4484f117d74a3f570 # v23.3.40
    secrets:
      GH_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
      BALENA_API_KEY: ${{ secrets.BALENA_API_KEY }}
    with:
      balena_slugs: "gh_klutchell/mediaserver"
      toggle_auto_merge: false
