name: Flowzone

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches: [main, master]
  push:
    branches: [main, master]

jobs:
  flowzone:
    name: Flowzone
    uses: product-os/flowzone/.github/workflows/flowzone.yml@072baab6e8aacb8145de181a97ef6948e9d8b188 # v23.3.9
    secrets:
      GH_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
      BALENA_API_KEY: ${{ secrets.BALENA_API_KEY }}
    with:
      balena_slugs: "gh_klutchell/mediaserver"
      toggle_auto_merge: false
