name: Flowzone

on:
  pull_request:
    types: [opened, synchronize, closed]
    branches: [main, master]
  push:
    branches: [main, master]

jobs:
  flowzone:
    name: Flowzone
    uses: product-os/flowzone/.github/workflows/flowzone.yml@758909bed87144172ec25c1cd27428c19c3ae5ba # v23.1.12
    secrets:
      GH_APP_PRIVATE_KEY: ${{ secrets.GH_APP_PRIVATE_KEY }}
      BALENA_API_KEY: ${{ secrets.BALENA_API_KEY }}
    with:
      balena_slugs: "gh_klutchell/mediaserver"
      toggle_auto_merge: false
